apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        smC8/angular-test-jx: true
        smC8/jenkinsx-node: true
        smC8/jx-angular: true
        smC8/jx-go: true
        smC8/jx-go-http: true
        smC8/jx-golang-http: true
        smC8/jx3-minikube: true
        smC8/jx3-node: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        smC8/angular-test-jx: merge
        smC8/jenkinsx-node: merge
        smC8/jx-angular: merge
        smC8/jx-go: merge
        smC8/jx-go-http: merge
        smC8/jx-golang-http: merge
        smC8/jx3-minikube: merge
        smC8/jx3-node: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - smC8/jx3-minikube
        - smC8/angular-test-jx
        - smC8/jenkinsx-node
        - smC8/jx-angular
        - smC8/jx-go-http
        - smC8/jx-go
        - smC8/jx-golang-http
        - smC8/jx3-node
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - smC8/jx3-minikube
        - smC8/angular-test-jx
        - smC8/jenkinsx-node
        - smC8/jx-angular
        - smC8/jx-go-http
        - smC8/jx-go
        - smC8/jx-golang-http
        - smC8/jx3-node
      target_url: http://lighthouse-jx.172.17.0.2.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
